language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.5
  - rbx-2.4.1
  - jruby-18mode
  - jruby-19mode

jdk:
  - openjdk7
  - oraclejdk8

matrix:
  exclude:
    - rvm: 1.8.7
      jdk: oraclejdk8
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.1.5
      jdk: oraclejdk8
    - rvm: rbx-2.4.1
      jdk: oraclejdk8
