language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.5
  - jruby-18mode
  - jruby-19mode

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

sudo: false

cache: bundler

matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk6
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.1.5
      jdk: openjdk6
    - rvm: 2.1.5
      jdk: openjdk7
    - rvm: 2.1.5
      jdk: oraclejdk7
